# Logging to console
logging = false

# Configure the http server
[server]
address = ":8000"
path = "/ctl"

# Configure the serial port
[serial]
port = "/dev/ttyUSB1"
baud = 9600

# Define commands
[commands]

    [commands.poweron]
    command = "POWR1" # Command sent to the TV
    hasParameter = false # Wont accept parameter in GET request

    [commands.poweroff]
    command = "POWR0"
    hasParameter = false

    [commands.input]
    command = "IAVD"
    hasParameter = true # Parameter value in GET request will be added

    [commands.avmode]
    command = "AVMD"
    hasParameter = true

    [commands.volume]
    command = "VOLM"
    hasParameter = true

    [commands.mute]
    command = "MUTE1"
    hasParameter = false

    [commands.unmute]
    command = "MUTE2"
    hasParameter = false
